version: '3.5'

services:
  boldbi:
   container_name: boldbi
   image: syncfusion/boldbi:8.3.17_eval
   restart: always
   ports:
     - 8085:80
   environment:
      # Required
     - BOLD_SERVICES_UNLOCK_KEY=<BOLD_SERVICES_UNLOCK_KEY>   # Set the unlock key value from the unlock_key.lic file, which can be obtained from the accounts page(https://www.boldbi.com/account).
      # Optional: Default values are fine for evaluation purposes.
     - BOLD_SERVICES_DB_TYPE=postgresql                      # Preconfigured PostgreSQL database details that are deployed along with this deployment.
     - BOLD_SERVICES_DB_HOST=localhost
     - BOLD_SERVICES_POSTGRESQL_MAINTENANCE_DB=postgres
     - BOLD_SERVICES_DB_USER=postgres
     - BOLD_SERVICES_DB_PASSWORD=Admin@123
     - BOLD_SERVICES_USER_EMAIL=testuser@boldbi.com          # Set the site admin user Mail ID.
     - BOLD_SERVICES_USER_PASSWORD=Admin@123                 # Set the site admin user password.
   networks:
     - boldbi
   volumes:
     - boldbi_data:/application/app_data
     - db_data:/var/lib/postgresql

networks:
  boldbi:
  
volumes:
  boldbi_data:
  db_data:
